# Generated by Django 2.0.5 on 2018-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
