# Generated by Django 2.0.5 on 2018-05-15 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20180514_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2018, 5, 15, 5, 31, 58, 574438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='user status'),
        ),
    ]
