# Generated by Django 2.0.5 on 2018-05-15 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20180515_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2018, 5, 15, 6, 28, 50, 826855, tzinfo=utc)),
        ),
    ]
